import { zohoPost, zohoGet } from "./client";
import { prisma } from "@/lib/db";

const MODULE_PRICES: Record<string, number> = {
  "CAT-I": 36000,
  "CAT-MES": 15000,
  "CAT-QT": 15000,
  "CAT-SCAN": 12000,
  "CAT-ALOG": 12000,
  "Full Platform": 90000,
};

async function findOrCreateZohoContact(customer: {
  company: string;
  contact: string;
  email: string;
  phone: string;
}): Promise<string> {
  // Search for existing contact by company name
  try {
    const search = await zohoGet<any>(
      `/contacts?contact_name_contains=${encodeURIComponent(customer.company)}`
    );
    if (search.contacts?.length > 0) {
      return search.contacts[0].contact_id;
    }
  } catch {
    // If search fails, proceed to create
  }

  const res = await zohoPost<any>("/contacts", {
    contact_name: customer.company,
    contact_type: "customer",
    contact_persons: [
      {
        first_name: customer.contact.split(" ")[0] || customer.contact,
        last_name: customer.contact.split(" ").slice(1).join(" ") || "",
        email: customer.email,
        phone: customer.phone,
        is_primary_contact: true,
      },
    ],
  });

  return res.contact?.contact_id;
}

export async function activateZohoBilling(customerId: number, force = false) {
  const customer = await prisma.customer.findUnique({
    where: { id: customerId },
    include: { owner: true },
  });
  if (!customer) return;

  // Skip if already has a Zoho customer ID (idempotent) unless forced
  if (customer.zohoCustomerId && !force) {
    console.log(`[zoho] Customer ${customer.company} already has Zoho ID ${customer.zohoCustomerId}`);
    return;
  }

  // Skip $0 contracts
  if (customer.contractValue <= 0) {
    console.warn(`[zoho] Skipping $0 contract for ${customer.company}`);
    await prisma.customer.update({
      where: { id: customerId },
      data: { billingStatus: "manual_review" },
    });
    return;
  }

  try {
    // 1. Create/find Zoho Books contact
    const zohoContactId = await findOrCreateZohoContact({
      company: customer.company,
      contact: customer.contact ?? "",
      email: customer.email ?? "",
      phone: customer.phone ?? "",
    });

    // 2. Build line items from modules
    const lineItems: Array<{ name: string; description: string; rate: number; quantity: number; item_total: number }> = [];

    if (customer.modules.length > 0) {
      for (const mod of customer.modules) {
        const price = MODULE_PRICES[mod] ?? 0;
        lineItems.push({
          name: `${mod} — Annual License`,
          description: `CAT-I.AI ${mod} module, annual contract`,
          rate: price,
          quantity: 1,
          item_total: price,
        });
      }

      // If modules sum doesn't match contract value, add an adjustment line
      const modulesTotal = lineItems.reduce((sum, li) => sum + li.rate, 0);
      if (modulesTotal !== customer.contractValue) {
        const diff = customer.contractValue - modulesTotal;
        if (diff !== 0) {
          lineItems.push({
            name: "Contract adjustment",
            description: "Adjustment to match contract value",
            rate: diff,
            quantity: 1,
            item_total: diff,
          });
        }
      }
    } else {
      // No modules — single line item for the full contract
      lineItems.push({
        name: "CAT-I.AI Platform — Annual License",
        description: "Annual platform contract",
        rate: customer.contractValue,
        quantity: 1,
        item_total: customer.contractValue,
      });
    }

    console.log(`[zoho] Creating invoice for ${customer.company}: ${lineItems.length} items, total $${lineItems.reduce((s, l) => s + l.item_total, 0)}`);

    // 3. Create invoice
    const invoiceRes = await zohoPost<any>("/invoices", {
      customer_id: zohoContactId,
      date: new Date().toISOString().slice(0, 10),
      payment_terms: 30,
      line_items: lineItems,
      notes: `Generated by CAT-I OPS on account conversion. Account manager: ${customer.owner?.name ?? "N/A"}`,
      is_inclusive_tax: false,
    });

    const invoiceId = invoiceRes.invoice?.invoice_id;
    const invoiceNumber = invoiceRes.invoice?.invoice_number;

    // 4. Update our customer record with Zoho IDs
    await prisma.customer.update({
      where: { id: customerId },
      data: {
        zohoCustomerId: zohoContactId,
        billingStatus: "invoiced",
      },
    });

    // 5. Log activity
    await prisma.activity.create({
      data: {
        who: customer.owner?.name ?? "System",
        action: "billing activated",
        target: customer.company,
        detail: `Invoice ${invoiceNumber ?? invoiceId} — $${customer.contractValue.toLocaleString()}, ${customer.modules.length} module${customer.modules.length !== 1 ? "s" : ""}`,
        type: "general",
      },
    });

    console.log(`[zoho] Invoice ${invoiceNumber} created for ${customer.company}`);
  } catch (err) {
    console.error(`[zoho] Failed to activate billing for ${customer.company}:`, err);
    // Don't throw — billing failure shouldn't block conversion
  }
}
